import fs from "fs";
import path from "path";
import type { AgentProvider } from "../routes/stories";

function fictionInstructions(): string {
  return `# Writing Instructions — Fiction

> Auto-generated by PlotLink OWS. Do not edit manually.
> For API endpoints and publish details, see ~/.plotlink-ows/CLAUDE.md.

## Story File Structure

\`\`\`
structure.md    — Story outline, characters, and arc
genesis.md      — Synopsis hook (~1000 chars)
plot-01.md      — Chapter 1 (max 10K chars)
plot-02.md      — Chapter 2
...
\`\`\`

## structure.md Format

### Required Sections

1. **Core Concept** — One paragraph describing the premise
2. **Main Characters** — For each character:
   - Age, Personality, Flaw, Arc
3. **Story Arc** — Beginning, Middle, End
4. **Chapter Plan** — Numbered list of planned chapters with one-line descriptions
5. **Progress Log** — Track what has been written

## genesis.md Format

The genesis is the story's hook — the first thing readers see on-chain.

- ~1000 characters (hard limit for on-chain genesis)
- Create immediate intrigue or emotional hook
- Introduce the core premise without spoilers
- End with a question or tension that pulls readers forward

## plot-NN.md Format

Each chapter is a self-contained prose section:

- Maximum 10,000 characters per file
- Number sequentially: plot-01.md, plot-02.md, etc.
- Each chapter should advance the story meaningfully
- Illustrations: upload via API, embed as \`![description](url)\` in markdown

## Publishing Rules

- Content is **immutable after publish** — verify everything in Preview first
- Genesis publishes via \`createStoryline\` (one-time per story)
- Plots publish via \`chainPlot\` (one per chapter)
- Always check character count before publishing (500–10,000 chars)
`;
}

/**
 * Provider-branched clean-image workflow section for cartoon instructions.
 *
 * The clean-image-first rules (no dialogue/SFX/bubbles/watermark/signature baked
 * into art) are shared; only the "who creates the file" contract differs:
 *
 * - Codex: creating the real `assets/plot-NN/cut-XX-clean.webp` file is the
 *   PRIMARY instruction, but it is gated behind a capability/checkpoint guardrail
 *   (#307) so the session never sits in an indefinite `Working` state: Codex
 *   makes one bounded attempt, and if image generation is unavailable it reports
 *   the blocker and falls back to the manual prompt + import path instead of
 *   hanging. Critically, Codex is never told it cannot create image files (#274)
 *   — only to verify-and-report rather than stall.
 * - Claude / legacy (absent provider): Claude does not generate image files in the
 *   terminal, so the manual prompt + import handoff stays primary (unchanged
 *   behavior).
 */
function cleanImageWorkflowSection(provider: AgentProvider): string {
  if (provider === "codex") {
    return `### Before generating images: confirm capability, checkpoint, and never hang (#307)

Image generation in this session is NOT guaranteed to be available. Before you
rely on it, follow this guardrail so the terminal never sits in an indefinite
\`Working\` state with no files and no blocker report:

1. **Checkpoint first, then make ONE bounded attempt.** Before generating, post a
   one-line status naming the file you are about to create (e.g. "generating
   cut-01 clean image"). Make exactly ONE attempt per file — never retry image
   generation in a loop or wait indefinitely for it to finish.
2. **Confirm the capability on that attempt.** If there is no working in-session
   image-generation capability — the attempt errors, returns no usable image
   bytes, or you cannot confirm it quickly — treat image generation as
   UNAVAILABLE for this session. (Per Asset Tooling, never shell out to
   \`magick\`/\`sharp\`/Playwright to fake it.)
3. **Fail visibly, never silently.** The moment image generation is
   unavailable/blocked, report it in one clear line — "Image generation is
   unavailable in this Codex session; switching to the prompt-and-import
   handoff." — then use the Fallback below and stop cleanly. An unreported hang
   is a bug; a clear blocker report is the correct, expected outcome.
4. **Report progress per file.** After each saved image or each blocker, post a
   one-line checkpoint ("cut 2/6 saved" / "cover saved" / "blocked: <reason>") so
   the writer always sees progress, never a bare spinner.

This guardrail applies to BOTH the cover and every clean cut image. Creating the
files is still your primary job when generation works (below); the rule is only
that you verify-and-report instead of stalling.

### Create the clean image file directly — your primary job

When image generation is available (confirm it per the guardrail above), for each
cut you CREATE THE REAL CLEAN-IMAGE FILE — you do not just return a prompt or
description. Follow this file contract exactly:

1. Generate the clean image for the requested cut from its shot type + description
   + characters (the OWS UI's per-cut "Copy prompt" gives you the exact visual
   prompt text if you need it).
2. Save it as \`assets/plot-NN/cut-XX-clean.webp\` (WebP, or JPEG) — use the
   episode's \`plot-NN\` folder and the cut's zero-padded id (\`cut-01\`, \`cut-02\`,
   …).
3. The image must contain NO text, captions, speech bubbles, SFX lettering,
   readable signage, watermark, or signature.
4. After saving, VERIFY the file actually exists at
   \`assets/plot-NN/cut-XX-clean.webp\`, is WebP or JPEG, and is under 1MB — before
   reporting success.
5. Do NOT claim the image was generated unless the file actually exists; then run
   the OWS "Sync clean images" action (or let OWS auto-detect it) to record
   \`cleanImagePath\` — never hand-write the path for a file that is not really
   there.

**Only exception:** Include text in an image when it is part of the physical scene
(a sign on a building, text on a screen, a letter being read) AND the writer has
explicitly requested it.

### Fallback: hand the prompt to the writer (only if image generation is unavailable)

If image generation is not available in this session, do not block — fall back to
the manual handoff for each cut:
1. PREPARE THE EXACT CLEAN-IMAGE PROMPT (shot type + description + characters +
   the no-text constraint). This is the same prompt the OWS UI exposes per cut.
2. Tell the writer to generate it externally (any provider/tool) and then
   upload/import the resulting WebP/JPEG into OWS using the per-cut "Copy prompt" +
   "Upload clean image" controls.
3. **Do NOT claim that \`assets/plot-NN/cut-XX-clean.webp\` was created unless the
   file actually exists.** Never report an image as generated when you only
   produced a prompt.

### Cover fallback (only if cover generation is unavailable)

The cover follows the same guardrail. If you cannot generate \`assets/cover.webp\`
in this session, do NOT hang on the cover: say so in one line and tell the writer
to import a cover via the OWS "Import generated image" control on the genesis
publish panel (it accepts a PNG and converts it). The same one-attempt-then-report
rule applies to a cover-only request.

### Finishing the task: post a completion line and STOP (#311)

You are DONE once every requested cut has been handled — each one either has its
verified clean-image file saved, OR a clear blocker reported and the
prompt-and-import fallback handed off — and the cover is saved or its fallback
reported. Verifying that each file exists at the right path, format, and size is
ALL the checking required.

Do NOT start an open-ended "let me visually re-inspect the images" loop: you
cannot meaningfully re-judge generated art from a terminal, and looping there is
exactly what leaves the OWS session stuck in a long-running \`Working\` state after
the files already exist.

Post ONE final completion line, then STOP (return to the idle prompt — do not keep
working or wait for more input):

  CARTOON ASSETS COMPLETE — N/N clean cut images saved, cover <saved|skipped>. Ready for lettering in OWS.

If some assets are blocked, use instead:

  CARTOON ASSETS PARTIAL — X/N clean cut images saved, Y blocked: <reasons>. Ready for lettering on the saved cuts in OWS.

After that line, the lettering/export/publish steps are the writer's job in OWS —
hand off and stop.`;
  }

  return `### You cannot create image files yourself — hand the prompt to the writer

You (Claude) do **not** generate image files in this terminal. You produce the
exact clean-image PROMPT for each cut; the writer (or a configured image tool, if
any) generates the actual image externally and imports it back into OWS.

If no image-generation tool is available in the terminal, for each cut:
1. PREPARE THE EXACT CLEAN-IMAGE PROMPT (shot type + description + characters +
   the no-text constraint). This is the same prompt the OWS UI exposes per cut.
2. Tell the writer to generate it externally (any provider/tool they prefer) and
   then upload/import the resulting WebP/JPEG into OWS using the per-cut
   "Copy prompt" + "Upload clean image" controls.
3. **Do NOT claim that \`assets/plot-NN/cut-XX-clean.webp\` was created unless the
   file actually exists.** Never report an image as generated when you only
   produced a prompt.
4. After a clean image file exists, update/verify the cut's \`cleanImagePath\`
   through the OWS import flow or the cuts API — do not invent the path.

If a configured image tool exists, it may generate the clean image directly;
otherwise the manual prompt + import path above is the safe baseline.

Saved clean images live at: \`assets/plot-NN/cut-XX-clean.webp\` (OWS records the
path; you do not hand-write it unless the file is really there).

**Only exception:** Include text in images when it is part of the physical scene
(a sign on a building, text on a screen, a letter being read) AND the writer
has explicitly requested it.`;
}

/** Provider-branched step 2 of the Episode Workflow checklist. */
function episodeWorkflowImageStep(provider: AgentProvider): string {
  if (provider === "codex") {
    return `2. **Generate** — Create the real clean-image file for each cut at
   \`assets/plot-NN/cut-XX-clean.webp\` and verify it exists. Checkpoint per file
   and make one bounded attempt; if image generation is unavailable, report the
   blocker and fall back to preparing the prompt for the writer to import —
   never sit in an indefinite \`Working\` state.`;
  }
  return `2. **Prompt & import** — Prepare the clean-image prompt for each cut; the writer
   generates it externally (or a configured image tool, if any) and uploads/
   imports the clean image via OWS. You do not create the image file yourself.`;
}

function cartoonInstructions(provider: AgentProvider): string {
  return `# Writing Instructions — Cartoon

> Auto-generated by PlotLink OWS. Do not edit manually.
> For API endpoints and publish details, see ~/.plotlink-ows/CLAUDE.md.

## Story File Structure

\`\`\`
.story.json              — { "contentType": "cartoon" }
structure.md             — Style guide, character bible, episode format
genesis.md               — Synopsis hook (~1000 chars, text only)
plot-NN.cuts.json        — Cut plan for episode NN
plot-NN.md               — Episode publish markdown (image sequence)
assets/
  plot-NN/
    cut-01-clean.webp    — Clean image (no text or bubbles)
    cut-01-final.webp    — Final lettered version
    ...
\`\`\`

## structure.md Format (Cartoon)

### Required Sections

1. **Visual Style Guide**
   - Art style (manga, Franco-Belgian, webcomic, American comic, etc.)
   - Color palette (full color, limited palette, monochrome + spot color)
   - Line weight and inking style
   - Panel/cut layout preferences (grid, dynamic, full-bleed)

2. **Character Bible**
   For each character, describe their VISUAL identity:
   - Physical features: hair color/style, eye color, build, height
   - Signature outfit and accessories
   - Distinguishing visual features (scars, glasses, tattoos)
   - Expression notes (resting expression, characteristic gestures)

3. **Episode Format**
   - Target cuts per episode (typical: 4–12)
   - Pacing rhythm: how to alternate wide/medium/close-up shots
   - Aspect ratio preference for cuts

4. **Bubble and Lettering Conventions**
   - Speech bubble style (round, angular, cloud-like)
   - Thought bubble style
   - Narration/caption box style
   - Sound effect (SFX) conventions
   - Font or lettering style preferences

5. **Cut Planning Rules**
   - Shot progression guidelines (e.g., establish → act → react)
   - When to use wide vs. close-up shots
   - Transition conventions between scenes

## genesis.md Format

Same as fiction: a prose synopsis hook, ~1000 characters. This is text only — no images.

- Create immediate intrigue or emotional hook
- Introduce the visual world and core premise
- End with tension that pulls readers forward

## Cut Planning — plot-NN.cuts.json

Before generating images for an episode, create the cut plan first. The cuts.json
is the single source of truth for the episode's visual sequence.

**CRITICAL: Use this EXACT schema. Do NOT invent alternate or nested planning
structures.** OWS reads this file with a strict validator — any other shape is
rejected.

Valid \`plot-01.cuts.json\`:

\`\`\`json
{
  "version": 1,
  "plotFile": "plot-01",
  "cuts": [
    {
      "id": 1,
      "shotType": "wide",
      "description": "Establishing shot of the rain-soaked city at dusk",
      "characters": ["Mira"],
      "dialogue": [
        { "speaker": "Mira", "text": "It always rains here." }
      ],
      "narration": "The city never slept, and neither did she.",
      "sfx": "RAIN",
      "cleanImagePath": null,
      "finalImagePath": null,
      "exportedAt": null,
      "uploadedCid": null,
      "uploadedUrl": null,
      "overlays": []
    }
  ]
}
\`\`\`

### Required field naming (do NOT use the wrong forms)

| Use this | NOT this |
|----------|----------|
| \`version: 1\` (top level) | \`$schema\`, \`story\`, \`workflow\`, \`promptDefaults\` |
| numeric \`id\` (1, 2, 3) | string ids like \`"c01"\` |
| \`shotType\` | \`shot\` |
| \`description\` | nested \`image.prompt\` |
| \`dialogue[].text\` | \`dialogue[].line\` |
| \`narration\` (string) | nested \`text.narration\` |
| \`sfx\` (single string) | \`sfx\` as an array |
| \`cleanImagePath\` / \`finalImagePath\` (top-level on the cut) | nested \`image.clean\` / \`image.final\` |

- \`shotType\` must be one of: \`wide\`, \`medium\`, \`close-up\`, \`extreme-close-up\`.
- All image/export/upload path fields start as \`null\`; OWS fills them in.
- \`overlays\` starts as an empty array \`[]\`; the lettering editor populates it.
  **Leave \`overlays\` empty (\`[]\`)** — the writer places bubbles/captions in the
  OWS lettering editor. If you ever do emit overlays, each MUST use the real OWS
  overlay schema below — NEVER a semantic \`position\` string like \`"upper-left"\`,
  which has no geometry, does not render, and would export a blank, unlettered
  image.
- **Overlay schema (only if you emit overlays):** each overlay is an object with
  \`id\` (string), \`type\` (\`"speech"\` | \`"narration"\` | \`"sfx"\`), numeric \`x\`, \`y\`,
  \`width\`, \`height\` (fractions of the image, 0–1, where \`x\`/\`y\` are the top-left
  corner), \`text\` (string), optional \`speaker\` (speech only), and optional
  \`tailAnchor\` (\`{ "x": number, "y": number }\`, speech only). Example:
  \`{ "id": "ov-1", "type": "speech", "x": 0.08, "y": 0.06, "width": 0.4, "height": 0.16, "text": "...", "speaker": "Hana", "tailAnchor": { "x": 0.5, "y": 1.2 } }\`.
  There is NO \`position\` field.
- **Every publishable cut must become a final uploaded image.** Even
  narration-only or background-only cuts must get a clean image, be lettered/
  exported, and uploaded before the episode can publish. \`cleanImagePath\` may
  be \`null\` during early planning, but a cut with no uploaded image will block
  publish readiness.

## Asset Tooling — use OWS flows, do NOT shell out to image tools

OWS owns the cartoon asset pipeline. Local image tools are NOT part of the
contract and may be absent — do **NOT** call ImageMagick (\`magick\`/\`convert\`/
\`identify\`), \`sharp\`, Playwright / headless browsers, or any ad-hoc shell tool to
resize, convert, composite, letter, or measure images. If you find yourself
reaching for a CLI image tool, STOP — there is a supported OWS action for it, and
guessing at unavailable tooling is exactly what stalls a cartoon episode.

**Deterministic handoff — who does what:**

| Step | Who | How (no shell image tools) |
|------|-----|----------------------------|
| Generate clean cut images | You (Codex) | Generate at the target size/format and save \`assets/plot-NN/cut-XX-clean.webp\` (WebP/JPEG, < 1MB). Produce it correctly at generation time — do NOT post-process with magick/sharp. |
| Generate the cover | You (Codex) | Save \`assets/cover.webp\` (~600x900, WebP, < 1MB). OWS auto-detects it for genesis publish — no manual selection needed. |
| Discover / record clean images | OWS | Run the "Sync clean images" action (or let OWS auto-detect); OWS records \`cleanImagePath\`. Never hand-write paths or stat files yourself. |
| Letter & export final images | The writer, in the OWS lettering editor | Speech bubbles, captions, and SFX are placed in the OWS editor and exported to \`assets/plot-NN/cut-XX-final.webp\`. You do NOT composite or letter text — not with magick, not with sharp, not at all. |
| Upload finals + build markdown | OWS | The writer runs "Upload & Prepare for Publish"; OWS uploads each final image and emits the publish markdown. You never hand-write \`plot-NN.md\`. |

**No agent-side image tools are required** — OWS provides image generation (your
session), clean-image sync, the lettering/export editor, and upload/markdown
generation. If a capability you genuinely need is missing (e.g. image generation
itself is unavailable in this session), do NOT improvise with shell tools: fall
back to the prompt-and-import handoff below and tell the writer, so the missing
capability surfaces immediately instead of after a dead-end path.

## CRITICAL: Clean-Image-First Workflow

**Do NOT bake dialogue, speech bubbles, sound effects, or any text into generated images.**

Clean images must contain:
- No speech bubbles
- No text overlays
- No sound effect text
- No narration captions
- No lettering of any kind

${cleanImageWorkflowSection(provider)}

## Character Consistency

- Reference the character bible from structure.md for EVERY image generation
- Maintain consistent visual traits across all cuts and all episodes
- Same hair, same eye color, same outfit unless the story dictates a change
- Note any intentional appearance changes in the cuts.json

## Lettering Handoff

After clean images are generated and approved by the writer:

1. The writer uses the OWS lettering editor to add speech bubbles and text
2. Lettered versions are saved as: \`assets/plot-NN/cut-XX-final.webp\` (the OWS
   editor's export writes this file — you do not create or composite it)
3. Do NOT attempt to add bubbles or text to images — only the writer controls
   lettering, via the OWS editor. Never composite text with \`magick\`, \`sharp\`,
   Playwright, or any other tool; lettering/export is not an agent shell task.
4. The publish markdown references final lettered images, not clean images

## Publish Markdown — plot-NN.md

**Do NOT hand-write plot-NN.md with image links.** OWS generates the publish
markdown from cuts.json after final images are uploaded. Hand-authored markdown
with local asset paths (\`assets/...\`) or placeholder URLs ("final image
pending") will be rejected by publish readiness checks.

Correct flow:

1. Upload final (lettered) images via OWS — this records the IPFS URL per cut in
   cuts.json (\`uploadedUrl\`).
2. Use OWS "Prepare episode for publish" / "Upload & Prepare for Publish" to produce
   plot-NN.md. OWS emits marker-delimited blocks:
   \`\`\`
   <!-- ows:cartoon-cut cut-001 start -->
   ![Cut 1 — Scene description](https://ipfs-gateway/...)
   <!-- ows:cartoon-cut cut-001 end -->
   \`\`\`
3. Cuts that are not yet uploaded produce a safe \`<!-- ... awaiting upload -->\`
   comment, never a fake image URL. Publish is blocked until all cuts upload.
4. Each image is WebP or JPEG, under 1MB. Total markdown under 10K characters.
5. Keep human-readable planning notes in cuts.json or structure.md — never as
   fake publish image links.

## Publishing Rules

- Content is **immutable after publish** — verify all images in Preview first
- Genesis publishes via \`createStoryline\` (one-time, text-only synopsis)
- Episodes publish via \`chainPlot\` (per episode, image-sequence markdown)
- Once published, images cannot be replaced or edited

## Episode Workflow

1. **Plan** — Create plot-NN.cuts.json with shot-by-shot breakdown
${episodeWorkflowImageStep(provider)}
3. **Review** — Writer reviews clean images, requests adjustments
4. **Letter** — Writer adds speech bubbles and text via lettering editor
5. **Upload** — Upload final lettered images to get IPFS URLs (recorded in cuts.json)
6. **Generate** — Use OWS to generate plot-NN.md from cuts.json (do not hand-write it)
7. **Preview** — Verify all images render correctly
8. **Publish** — Chain the episode (immutable after this step)
`;
}

export function generateStoryInstructions(
  contentType: "fiction" | "cartoon",
  // Cartoon instructions branch by provider so a Codex cartoon session is told to
  // create the real clean-image file, while Claude/legacy sessions get the manual
  // prompt-and-import handoff. Fiction ignores provider (always Claude). Absent ⇒
  // "claude" (matches the fiction-safe absent⇒Claude default; see #268).
  provider: AgentProvider = "claude",
): string {
  if (contentType === "cartoon") return cartoonInstructions(provider);
  return fictionInstructions();
}

const MARKER_PREFIX = "<!-- plotlink-ows:story-instructions:";

// Cartoon markers encode the provider so a story repaired Claude⇒Codex (or vice
// versa) regenerates its CLAUDE.md on the next spawn instead of keeping stale,
// provider-mismatched wording. Fiction has no provider variant — its marker is
// unchanged for rollback safety.
function marker(contentType: "fiction" | "cartoon", provider: AgentProvider): string {
  const suffix = contentType === "cartoon" ? `cartoon:${provider}` : "fiction";
  return `${MARKER_PREFIX}${suffix} -->`;
}

export function writeStoryInstructions(
  storyDir: string,
  contentType: "fiction" | "cartoon",
  provider: AgentProvider = "claude",
): void {
  const claudeMdPath = path.join(storyDir, "CLAUDE.md");
  const expectedMarker = marker(contentType, provider);

  if (fs.existsSync(claudeMdPath)) {
    try {
      const firstLine = fs.readFileSync(claudeMdPath, "utf-8").split("\n")[0];
      if (firstLine === expectedMarker) return;
      if (!firstLine.startsWith(MARKER_PREFIX)) return;
    } catch { /* regenerate on error */ }
  }

  const content = expectedMarker + "\n" + generateStoryInstructions(contentType, provider);
  fs.writeFileSync(claudeMdPath, content, "utf-8");
}
